version: '2'

services:
  unifi:
    image: linuxserver/unifi
    container_name: unifi
    restart: always
    environment:
      PUID: 0
      PGID: 0
    volumes:
      - "/mnt/data/docker/unifi/config:/config"
    ports:
     - "9058:8080"
     - "8081:8081"
     - "8443:8443"
     - "8843:8843"
     - "8880:8880"
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    restart: always
    environment:
      VERSION: latest
      PUID: 0
      PGID: 0
    volumes:
      - "/mnt/data/docker/plex/config:/config"
      - "/mnt/media/series:/data/tvshows"
      - "/mnt/media/movies:/data/movies"
      - "/etc/localtime:/etc/localtime:ro"
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    restart: always
    volumes:
      - "/mnt/data/docker/plexpy/config:/config"
      - "/mnt/data/docker/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: 0
      PGID: 0
    ports:
      - "9055:8181"
  plexrequests:
    image: linuxserver/plexrequests
    container_name: plexrequests
    restart: always
    volumes:
      - "/mnt/data/docker/plexrequests/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: 0
      PGID: 0
    ports:
      - "9051:3000"
  sabnzdb:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    restart: always
    volumes:
      - "/mnt/data/docker/sabnzdb/config:/config"
      - "/mnt/data/downloads:/data"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: 0
      PGID: 0
    ports:
      - "9052:8080"
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "9053:8989"
    environment:
      PUID: 0
      PGID: 0
    volumes:
      - "/mnt/data/docker/sonarr/config:/config"
      - "/mnt/data/downloads:/data"
      - "/mnt/data/downloads:/downloads"
      - "/mnt/media/series/:/media"
      - "/etc/localtime:/etc/localtime:ro"
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "9054:7878"
    environment:
      PUID: 0
      PGID: 0
    volumes:
      - "/mnt/data/docker/radarr/config:/config"
      - "/mnt/data/downloads:/data"
      - "/mnt/media/movies/:/media"
      - "/mnt/media/movies/:/movies"
      - "/etc/localtime:/etc/localtime:ro"
  muximux:
    image: linuxserver/muximux
    container_name: muximux
    restart: always
    ports:
      - "9050:80"
    volumes:
      - "/mnt/data/docker/muximux/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    restart: always
    environment:
      PUID: 0
      PGID: 0
    env_file:
      - duckdns.env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
  ha:
    image: homeassistant/home-assistant:latest
    container_name: ha
    restart: always
    ports:
      - "9056:8123"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/data/docker/ha/config:/config"
    devices:
      - '/dev/zwave:/dev/zwave:rwm'
    links:
      - mqtt
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "9057:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/data/docker/portainer:/data"
  mqtt:
    image: matteocollina/mosca
    container_name: mqtt
    restart: always
    ports:
      - 1883:1883
  mqttbridge:
    image: stjohnjohnson/smartthings-mqtt-bridge
    container_name: mqttbridge
    restart: always
    volumes:
      - "/mnt/data/docker/mqttbridge/config:/config"
    ports:
      - 8080:8080
    links:
      - mqtt
